### ISSUE TITLE
Fix CSS overlap

### ISSUE THREAD

**Issue by GCUCoding** [GCUCoders/Tech-Club-Site#13]

**Comment by GCUCoding** [comment]
Please fix the broken CSS files

**Comment by elijaholmos** [comment]
I'm going to hold off on this until the coders have merged their commits for the night, since there may be additional conflicts that arise later if I fix this now

**Comment by GCUCoding** [comment]
Same, sounds good.

**Comment by elijaholmos** [comment]
This is a test to see if our webhook was triggered.
