### ISSUE TITLE
Fix the two-body tag issue in Merch.html

### ISSUE THREAD

**Issue by GCUCoding** [GCUCoders/Tech-Club-Site#40]
![image](https://user-images.githubusercontent.com/77521006/142568219-8de29ea3-4fa0-4b32-97b5-72e5614dc21c.png)
>If you need assistance, please don't be afraid to reach out.
**HTML tags can have multiple attributes and multiple classes**

**Comment by ponyboy14** [comment]
Fixed two body issue
