### ISSUE TITLE
Fix bad javascript link on about.html

### ISSUE THREAD

**Issue by GCUCoding** [GCUCoders/Tech-Club-Site#43]
![image](https://user-images.githubusercontent.com/77521006/142569662-86d26884-a172-488e-b1eb-7cf728ef9d65.png)
Currently leads to club.js, which does not exist. As there are no JS functions used on the page, feel free to leave empty until a future commit. **There simply needs to be a name change on about.html and a new file created to go with about.html's JS code to resolve this issue.**

**Comment by elijaholmos** [comment]
resolved with bc25c9ce5435db0b9b2d29e006f63b58bbd512b2
